school/urls.py
from . import views
from django.urls import path ,include


app_name='school'

urlpatterns = [
    
    path('', views.CategoryListView.as_view(), name='category_list'),
    path('<slug:slug>/', views.CategoryListView.as_view(), name='category_list'),
    path('post_list/<str:category>/<slug:slug>/', views.PostListView.as_view(), name='post_list'),
    path('tags/<slug:tag_slug>/', views.TagIndexView.as_view(), name='posts_by_tag'),
    path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_detail/<str:category>/<str:name>/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),

    path('search_results', views.search_results, name='search_results'),
   # path('<str:post>/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    #path('post_create/<str:category>/<int:pk>/create/', views.PostCreateView.as_view(), name='post_create'),
    path('<str:category>/<slug:slug>/update/', views.PostUpdateView.as_view(), name='post_update'),
    path('<str:category>/<slug:slug>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path('tinymce/', include('tinymce.urls')),
]

smart_learn/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
import users
import school

urlpatterns = [
    path('', include('users.urls')),
    path('school', include('school.urls')),
    path('admin/', admin.site.urls),
 
]




from django.conf import settings
from django.conf.urls.static import static
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)


admin.site.site_header = "All PC Solutions AdminPanel"
admin.site.site_title = "All PC Solutions App Admin"
admin.site.site_index_title = "Welcome To All PC Solutions Admin Panel"

users/urls.py
from django.urls import path, include
from users import views


#app_name = 'users'
urlpatterns = [
    path('', views.HomeView.as_view(), name='index'),

    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),

    path('contact/', views.ContactView.as_view(), name="contact"),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('forgotPassword/', views.forgotPassword, name='forgotPassword'),
    path('resetpassword_validate/<uidb64>/<token>/', views.resetpassword_validate, name='resetpassword_validate'),
    path('resetPassword/', views.resetPassword, name='resetPassword'),
    path('change_password/', views.change_password, name='change_password'),

    path('dmca/', views.DmcaView.as_view(), name="dmca"),
    path('privacy/', views.PrivacyView.as_view(), name="privacy"),
    path('terms/', views.TermsView.as_view(), name="terms"),
    path('about/', views.AboutView.as_view(), name="about"),


    

]

school/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.contrib.auth.models import User
import os
from embed_video.fields import EmbedVideoField
from tinymce.models import HTMLField
from taggit.managers import TaggableManager
from users.models import Account

def save_category_image(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    #Get filename
    if instance.category_id:
        filename = 'Category_Picture/{}.{}'.format(instance.category_id, ext)
    return os.path.join(upload_to, filename)



class Category(models.Model):   #category #subject
    id = models.AutoField(primary_key=True)
    category_id = models.CharField(max_length=200, unique=True)
    category_name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(unique=True , null=True, blank=True)
    image = models.ImageField(upload_to=save_category_image, blank=True, verbose_name='Category Image')
    description = HTMLField(max_length=1000, blank=True, null=True)


    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.category_name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_id)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('school:post_list', args=[self.id,])

def save_post_files(instance, filename):
    upload_to = 'Images/'
    ext = filename.split('.')[-1]
    #Get filename
    if instance.post_id:
        fielname = 'post_files/{}/{}.{}'.format(instance.post_id, instance.post_id, ext)
        if os.path.exists(filename):
            new_name = str(instance.post_id) + str('1')
            filename = 'Post_images/{}/{}.{}'.format(instance.post_id, new_name, ext)
    return os.path.join(upload_to, filename)


class Post(models.Model): #POst list #lesson
    id = models.AutoField(primary_key=True)
    tags = TaggableManager()
    post_id = models.CharField(max_length=200, unique=True)
    created_by = models.ForeignKey(Account, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='posts')
    name = models.CharField(max_length=250)
    position = models.PositiveBigIntegerField(verbose_name="Post no.")
    slug = models.SlugField(unique=True, null=True, blank=True)
    image = models.ImageField(upload_to=save_post_files, blank=True, verbose_name='Post Image')
    description = HTMLField(blank=True, null=True)
    videolink = EmbedVideoField(verbose_name="Video link", blank=True, null=True)  
    filelink = models.URLField(blank=True, null=True)
    


    class Meta:
        ordering = ['-position']

    def __str__(self):
        return self.name

    def total_views(self):
        return self.views.count()


    def total_likes(self):
        return self.likes.count()


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('school:post_list', args=[self.id,])


class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    post_name = models.ForeignKey(Post, null=True, on_delete=models.CASCADE, related_name='comments')
    comm_name = models.CharField(max_length=200, blank=True)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    body = models.TextField(max_length=1000)
    date_added = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        self.comm_name = slugify("comment by" + "-" + str(self.user) + str(self.date_added))
        super().save(*args, **kwargs)

    def __str__(self):
        return self.comm_name

    class Meta:
        ordering = ['-date_added']

    
class Reply(models.Model):
    id = models.AutoField(primary_key=True)
    comment_name = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
    reply_body = models.TextField(max_length=500)
    user = models.ForeignKey(Account, on_delete=models.CASCADE)
    date_added = models.DateTimeField(auto_now_add=True)


    class Meta:
        verbose_name = 'Reply'
        verbose_name_plural = 'Replies'

    def __str__(self):
        return "reply to " + str(self.comment_name.comm_name)

school/forms.py
from django import forms
from .models import Comment, Reply, Post
from django.contrib.auth.models import User
from users.models import Account


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('post_id', 'name', 'position', 'videolink', 'filelink')



class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

        labels = {"body":"Comment:"}

        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'rows':4, 'cols':70, 'placeholder':"Write your comment"}),
        }

class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ('reply_body',)

        widgets = {
            'reply_body': forms.Textarea(attrs={'class':'form-control', 'rows':2, 'cols':10}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ReplyForm, self).__init__(*args, **kwargs)

school/views.py
from django.shortcuts import render
from django.views.generic import (TemplateView, DetailView,
                                    ListView, CreateView,
                                    UpdateView, DeleteView, FormView,)
from .models import Category, Post, Comment, Reply

from django.urls import reverse_lazy
from .forms import CommentForm, ReplyForm, PostForm
from django.http import HttpResponseRedirect
from taggit.models import Tag
from django.contrib.auth.models import User
from users.models import Account

class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context


def search_results(request):
    posts = Post.objects.order_by('-created_at')
    categories = Category.objects.all()

    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        if keyword:
            posts = posts.filter(description__icontains=keyword)

    data = {
        'posts': posts,
        'categories': categories,
    }
    return render(request, 'blog/search_results.html', data)


class CategoryListView(ListView):
    context_object_name = 'categories'
    model = Category
    template_name = 'blog/category_list_view.html'
    

class PostListView(TagMixin, DetailView):
    context_object_name = 'categories'
    model = Category
    template_name = 'blog/post_list_view.html'
    order_by = ['-created_at']


class TagIndexView(TagMixin, DetailView):
    model = Post
    template_name = 'blog/post_list_view.html'
    context_object_name = 'posts'

    def get_queryset(self):
        return Post.objects.filter(tags__slug=self.kwargs.get('tag_slug'))


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
        
class PostDetailView(DetailView,  FormView):
    context_object_name = 'posts'
    extra_context = {
        'categories': Category.objects.all()
    }
    model = Post
  
    template_name = 'blog/post_detail_view.html'
    form_class = CommentForm
    second_form_class = ReplyForm

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        if 'form' not in context:
            context['form'] = self.form_class(request=self.request)
        if 'form2' not in context:
            context['form2'] = self.second_form_class(request=self.request)
        # context['comments'] = Comment.objects.filter(id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        if 'form' in request.POST:
            form_class = self.get_form_class()
            form_name = 'form'
        else:
            form_class = self.second_form_class
            form_name = 'form2'

        form = self.get_form(form_class)
        # print("the form name is : ", form)
        # print("form name: ", form_name)
        # print("form_class:",form_class)

        if form_name =='form' and form.is_valid():
            print("comment form is returned")
            return self.form_valid(form)
        elif form_name=='form2' and form.is_valid():
            print("reply form is returned")
            return self.form2_valid(form)
    
    def get_success_url(self):
            self.object = self.get_object()
            category = self.object.category
            name = self.object.name
            return reverse_lazy('school:post_detail', kwargs={'category':category.slug,
                                                                'name':name,
                                                                'slug':self.object.slug})

    def form_valid(self, form):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.user = self.request.user
        fm.post_name = self.object.comments.name
        fm.post_name_id = self.object.id
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

    def form2_valid(self, form):  
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.user = self.request.user
        fm.comment_name_id = self.request.POST.get('comment.id')
        fm.save()
        return HttpResponseRedirect(self.get_success_url())


    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        return self.render_to_response(context)



class PostCreateView(CreateView):
    # fields = ('lesson_id','name','position','image','video','ppt','Notes')
    form_class = PostForm
    context_object_name = 'post'
    model = Post
    template_name = 'blog/post_create.html'

    def get_success_url(self):
        self.get_object()
        category = self.object.category
        return reverse_lazy('school:post_list', kwargs={'category':category.slug,
                                                        'slug':self.object.slug})

    def form_valid(self, form, *args, **kwargs):
        self.object = self.get_object()
        fm = form.save(commit=False)
        fm.created_by = self.request.user
        fm.Category = self.object.category
        fm.post = self.object
        fm.save()
        return HttpResponseRedirect(self.get_success_url())

class PostUpdateView(UpdateView):
    fields = ('name', 'position', 'video', 'filelink', 'ppt', 'Notes')
    model = Post
    template_name = 'blog/post_update.html'
    context_object_name = 'posts'


class PostDeleteView(DeleteView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blog/post_delete.html'

    def get_success_url(self):
        print(self.object)
        category = self.get_object.Category
        post = self.object.post
        return reverse_lazy('school:post_list', kwargs={'category':category.slug, 'slug':post})

school/templates/blog/category_list_view.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Categories {% endblock %}


{% block content %}
    <!-- ==========Page Header Section Start Here========== -->
    <section class="page-header-section style-1">
        <div class="container">
            <div class="page-header-content">
                <div class="page-header-inner">
                    <div class="page-title">
                        <h2>Choose A Category From List</h2>
                    </div>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'index' %}">Home</a></li>
                        <li><a href="{% url 'school:category_list' %}">Categories | Categories</a></li>                                   
                    </ol>
                </div>
            </div>
        </div>
    </section>
    <!-- ==========Page Header Section Ends Here========== -->


    <!-- ==========Activity Section start Here========== -->
    <section class="activity-section padding-top padding-bottom">
        <div class="container">

            <div class="section-wrapper">
                <div class="row">
                    <div class="col-xl-8">
                        <div class="section-header">
                            <h3>List Of Categories</h3>
                            <div class="nft-filter d-flex flex-wrap justify-content-center gap-15">
                                <div class="form-floating">
                                    
                                   
                                </div>
                            </div>
                        </div>
                        <div class="activity-wrapper">
                            <div class="row gy-3">
                              {% for category in categories.all %}
                                <div class="col-12">
                                    <div class="activity-item">
                                        <div class="lab-inner d-flex flex-wrap align-items-center p-3 p-md-4">
                                            <div class="lab-thumb me-3 me-md-4">
                                                <a href="{% url 'school:post_list' slug=category.slug category=category.slug %}">
                                                <img src="{{ category.image.url|default_if_none:'#' }}" height="100" width="200" alt="img">
                                                </a>
                                            </div>
                                            
                                            <div class="lab-content">
                                              <br>
                                                <h4><a href="{% url 'school:post_list' slug=category.slug category=category.slug %}">{{ category.category_name }}</a>
                                                </h4>
                                                <p class="mb-2">
                                                  {{ category.description|safe|truncatechars:75 }}
                                                </p>                                       
                                                <a href="{% url 'school:post_list' slug=category.slug category=category.slug %}" class="btn btn-primary" btn-sm
                                                style="background-color:#00bcd4;">
                                                <p><span><i data-blast="color"></i></span>
                                                  View Posts In Category
                                                </p>
                                            </a>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                              {% endfor %}               
                            </div>
                           
                        </div>
                    </div>
                    <!-- Aside Part -->
                    <div class="col-xl-4">
                        
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!-- ==========explore Section ends Here========== -->

{%endblock%}

school/templates/blog/post_detail_view.html
{% extends 'base.html' %}
{% load embed_video_tags %}

{% load crispy_forms_tags %}

{% load static %}
{% load social_share %}

{% block title %} {{posts.name}} {% endblock %}

{% block content %}

<!-- ==========Page Header Section Start Here========== -->
<section class="page-header-section style-1">
    <div class="container">
        <div class="page-header-content">
            <div class="page-header-inner">
                <div class="page-title">
                    <h2>Post No: {{ posts.position }} - {{ posts.name }}</h2>
                </div>
                <ol class="breadcrumb">
                    <br><br>
                    
                    <li><a href="#">Found In {{ posts.category }}</a></li>  
                                 
                </ol>
            </div>
        </div> 
    </div>
</section>
<!-- ==========Page Header Section Ends Here========== -->
                              
<!-- ==========Blog Section start Here========== -->
<section class="blog-section padding-top padding-bottom">
    <div class="container">
        <div class="main-blog">
            <div class="row g-5">
                <div class="col-xl-9 col-12">
                    <div class="blog-wrapper">
                        <div class="post-item">
                            <div class="post-item-inner">                               
                                <div class="post-content" align="center">
                                    <span class="meta" style="color:#ffffff">
                                        Created By: {{ posts.created_by.username|title }} | Posted {{ posts.created_at|timesince }} Ago                                 
                                    </span>        
                                    <h4 style="color: rgb(255, 111, 0);">SPREAD THE LOVE - SHARE THIS AMAIZING POST:</h4>
                                    {% post_to_facebook object_or_url "Post to Facebook!" %}
                                    {% post_to_twitter "Find this amazing site to download free Creative resources: softwares, plugins, VFX, Graphic Design, HTML templates, WebPress Themes Online Tutorials and much more ... {{object.title}}. Check it out!" object_or_url "Post to Twitter" %}
                                    {% post_to_linkedin object_or_url %}
                                    {% send_email object.title "Find this amazing site to download free Creative resources: softwares, plugins, VFX, Graphic Design, HTML templates, WebPress Themes Online Tutorials and much more ... {{object.title}}. Check it out!" object_or_url "Share via email" %}
                                    {% post_to_reddit "Find this amazing site to download free Creative resources: softwares, plugins, VFX, Graphic Design, HTML templates, WebPress Themes Online Tutorials and much more ... {{object.title}}" object_or_url %}
                                    {% post_to_telegram "Find this amazing site to download free Creative resources: softwares, plugins, VFX, Graphic Design, HTML templates, WebPress Themes Online Tutorials and much more ... {{object.title}}" object_or_url %}
                                    {% post_to_whatsapp "Find this amazing site to download free Creative resources: softwares, plugins, VFX, Graphic Design, HTML templates, WebPress Themes Online Tutorials and much more ..." object_or_url "Share via WhatsApp" %}
                                    {% save_to_pinterest object_or_url %}
                                    {% add_pinterest_script %}
                                                              
                                    <br>
                                                              
                                    <div class="lab-thumb me-3 me-md-4">
                                        <img src="{{ posts.image.url}}" height="10" width="700" alt="img">                                  
                                    </div>
                                    <br>
                                    <div>
                                        <p>
                                            {{ posts.description|safe }}
                                        </p>
                                    </div>
                                    <hr>                                 
                                   
                                    {% if posts.filelink %}
                                   
                                    <a href="{{ posts.filelink }}" download class="btn btn-primary btn-lg"
                                        style="background-color:#00bcd4;">
                                        <button type="button" class="btn btn-warning btn-lg btn-bloc">Download File</button>   
                                    </a>
                                    <a href="{{ posts.filelink }}" download class="btn btn-primary btn-lg"
                                    style="background-color:#00bcd4;">
                                    <button type="button" class="btn btn-warning btn-lg btn-bloc">PASSWORD: 123</button>   
                                </a>

                                    {% else %}
                                    <p class="card-text">File Still Uploading</p>
                                    {% endif %}
                                    <br><br>
                                    
                                    <br><br>
                                    {% if user.is_superuser %}
                                    <div class="col-md-6 mb-3 text-center">
                                        <a href="##"
                                            class="btn btn-warning btn-lg mr-4 btn-block">Update Lesson</a>
                                    </div>
                                    <div class="col-md-6">
                                        <a href="#"
                                            class="btn btn-danger btn-lg mr-4 btn-block"> Delete Lesson </a>
                                    </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="post-thumb">
                            <div class="row d-flex justify-content-center mb-4">
                                <div id="player-overlay">                                  
                                    {% if posts.video %}
                                        <video controls width="720" height="360">
                                            <source src="{{ posts.videolink.url }}" type="video/mp4">
                                        </video>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div id="comments" class="comments">
                            <div class="widget-title">
                                <br>
                                <span align="center">
                                    <h5 style="color: rgb(255, 111, 0);">Questions And Queries</h5>
                                    <h3 style="color: rgb(255, 111, 0);">Must Be Logged In To Comment Below</h3>
                                </span>
                            </div>                                                                       
                        <div class="container row">
                            <div class="col-md-6">
                                <form method="post">
                                    <div class="form-group">
                                    {% csrf_token %}
                                    {{form|crispy}}
                                    <input type="submit" name="form" value="Add Comment" class="btn btn-primary btn-sm">
                                    </div>
                                </form>                             
                            </div>
                        </div>
                        <div class="row">
                            {% for comment in posts.comments.all %}
                            <div class="col-md-8 mt-2 mb-2">
                                            <div class="media border p-3">
                                                <img src="{% static 'Images/user_avatar.png' %}" alt="John Doe" class="mr-3 mt-3 rounded-circle" style="width:60px;">
                                                <div class="media-body">
                                                        <h4>{{comment.user.username}} <small><i>Commented on: {{comment.date_added}}</i></small></h4>
                                                        <p>{{comment.body}}</p>
                                                {% for reply in comment.replies.all %}
                                                            <div class="media p-3">
                                                                    <img src="{% static 'Images/user_avatar.png' %}" alt="Jane Doe" class="mr-3 mt-3 rounded-circle" style="width:45px;">
                                                            <div class="media-body">
                                                                    <h5>{{reply.user.username}} <small><i>Replied on {{reply.date_added}}</i></small></h5>
                                                                    <p>{{reply.reply_body}}</p>
                                                                </div>
                                                            </div>
                                                {% endfor %}
                                                <!-- form to post reply -->
                                                <form method="post">
                                                        <input type="hidden" name="comment.id" value="{{comment.id}}">
                                                        <input type="hidden" name="comment.comm_name" value="{{comment.comm_name}}">
                                                        {% csrf_token %}
                                                        {{form2.as_p}}
                                                        <input type="submit" name="form2" value="Add Reply" class="btn btn-warning btn-sm">
                                                </form>
                                                </div>
                                        </div>
                            </div>
                            {% endfor %}
                        </div>
                        
                       
                        </div>

                       
                    </div>
                </div>
                <div class="col-xl-3 col-12">
                    <aside>
                        <div class="profile-widget search-widget">
                            <div class="widget-inner">
                                <div class="widget-title">
                                    <h5>Search Post</h5>
                                </div>
                                <div class="widget-content">
                                    <p>Search from the newest post collections</p>
                                    <div class="form-floating nft-search-input">
                                        <form action="{% url 'school:search_results' %}">
                                            <input type="search" class="form-control" id="nftSearch"
                                                placeholder="Search post" name="keyword">
                                            <label for="nftSearch">Search post</label>
                                            <button type="button"> <i class="icofont-search-1"></i></button>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                        <div class="widget widget-category">
                            <div class="widget-header">
                                <h5 class="title">Post Category</h5>
                            </div>
                            <ul class="widget-wrapper">
                                {% for category in categories.all %}
                                <li>
                                    <a href="{% url 'school:post_list' slug=category.slug category=category.slug %}" class="d-flex flex-wrap justify-content-between"><span><i
                                                class="icofont-double-right"></i>{{ category.category_name }}</span></a>
                                </li>
                                {% endfor %}                              
                            </ul>
                        </div>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- ==========Blog Section ends Here========== -->

{% endblock %}